# Generated by Django 3.2.3 on 2021-06-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210604_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
